trigger:
- main
pool: mslearn-tailspin-spacegame-web-agent

variables:
  buildConfiguration: 'Release'
steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build --configuration $(buildConfiguration)'